### ISSUE TITLE
Question on 05-asynchronous-control-flow-patterns-with-promises-and-async-await/03-promises-web-spider-v2

### ISSUE THREAD

**Issue by OpenTechConsult** [PacktPublishing/Node.js-Design-Patterns-Third-Edition#57] opened 2022-08-18 11:54 UTC
Hello Mario & Luciano,

I hope you don't mind me asking a question about your new book "Node.js Design Pattern"  Third Edition. I've been looking for ways to reach out to you.

I've been studying Node.js for some time now, I must admit that the level of the book is tiny a bit high, but I am keeping up.

When I follow the example in [05-asynchronous-control-flow-patterns-with-promises-and-async-await/03-promises-web-spider-v2](https://github.com/PacktPublishing/Node.js-Design-Patterns-Third-Edition/tree/master/05-asynchronous-control-flow-patterns-with-promises-and-async-await/03-promises-web-spider-v2) I got an error when I use the latest version of `mkdirp` which is version "^1.0.4".  

I am getting an error **on line 16 of the spider.js** module.  

`return mkdirpPromises(dirname(filename))`

Here are the details of the error

>  TypeError: invalid options argument
>     at optsArg (/Users/eagboka/Documents/GitHub/promises-web-spider-v2/node_modules/mkdirp/lib/opts-arg.js:13:11)
>     at mkdirp (/Users/eagboka/Documents/GitHub/promises-web-spider-v2/node_modules/mkdirp/index.js:11:10)
>     at /Users/eagboka/Documents/GitHub/promises-web-spider-v2/lib/internal/util.js:360:7
>     at new Promise (<anonymous>)
>     at mkdirp (/Users/eagboka/Documents/GitHub/promises-web-spider-v2/lib/internal/util.js:346:12)
>     at /Users/eagboka/Documents/GitHub/promises-web-spider-v2/spider.js:16:20
>     at processTicksAndRejections (node:internal/process/task_queues:96:5) {stack: 'TypeError: invalid options argument
>     at op…ions (node:internal/process/task_queues:96:5)', message: 'invalid options argument'}

But when I use "mkdirp" version 0.5.1 I don't get the error and everything works fine.
Wouldn't there be a way to solve this problem or else we are condemned to use version 0.5.1 of this module?

Thanks, 
Sandro Agboka
OpenTech-Consult
Lomé, Togo

**Comment by mariocasciaro** [comment] 2022-09-08 12:46
Duplicate of #58

**Closed as completed by mariocasciaro** 2022-09-08 12:46 UTC
